default:
  gherkin:
    filters:
      tags: ~@javascript
  suites:
    default:
      paths:
        - "%paths.base%/tests/features"
      contexts:
        - Drupal\DrupalExtension\Context\ConfigContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Digipolisgent\QA\Drupal\Behat\Context\AccessContext
        - Digipolisgent\QA\Drupal\Behat\Context\DebugContext:
            path: "%paths.base%/tests/features/dumps"
        - Digipolisgent\QA\Drupal\Behat\Context\UriContext
        - Digipolisgent\QA\Drupal\Behat\Context\SelectorContext
  extensions:
    Drupal\MinkExtension:
      browserkit_http: ~
      selenium2: ~
      sessions:
        default:
          browserkit_http: ~
        javascript:
          selenium2:
            wd_host: "http://localhost:4444/wd/hub"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
      drush:
        root: "%paths.base%/web"
      drupal:
        drupal_root: "%paths.base%/web"
      region_map:
        header: ".header"
        content: ".region-content"
      selectors:
        message_selector: ".messages"
        error_message_selector: ".messages.messages--error"
        success_message_selector: ".messages.messages--status"
